### ISSUE TITLE
Difference between Rapidfuzz JaroWinkler and this

### ISSUE THREAD

**Issue by JoshuaBWT** [maxbachmann/JaroWinkler#15]
Hi,

First, thanks for the great work! Rapidfuzz and this are killers in terms of performance and usability!

I only have one question: What are the differences between using rapidfuzz python implementation of jaronwinkler (rapidfuzz.distance.JaroWinkler.similiarity) and this library aside from just the API?

Regards,
Joshua

**Comment by maxbachmann** [comment]
Historically I packaged jarowinkler in a separate package. However since this made the whole release process more complex I included the implementation directly in the rapidfuzz package since [v2.11.0](https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.11.0).

The API is the only difference between the two. At some point I will probably convert this library to a thin wrapper around the implementation in rapidfuzz to reduce the maintenance burden.

**Comment by JoshuaBWT** [comment]
well this
```
if processor is not None:
        s1 = processor(s1)
        s2 = processor(s2)

    if score_cutoff is None:
        score_cutoff = 0

    P_len = len(s1)
    T_len = len(s2)
    min_len = min(P_len, T_len)
    prefix = 0
    max_prefix = min(min_len, 4)

    for _ in range(max_prefix):
        if s1[prefix] != s2[prefix]:
            break
        prefix += 1

    jaro_score_cutoff = score_cutoff
    if jaro_score_cutoff > 0.7:
        prefix_sim = prefix * prefix_weight

        if prefix_sim >= 1.0:
            jaro_score_cutoff = 0.7
        else:
            jaro_score_cutoff = max(
                0.7, (prefix_sim - jaro_score_cutoff) / (prefix_sim - 1.0)
            )

    Sim = Jaro.similarity(s1, s2, score_cutoff=jaro_score_cutoff)
    if Sim > 0.7:
        Sim += prefix * prefix_weight * (1.0 - Sim)

    return Sim if Sim >= score_cutoff else 0
```
and this
```
 if processor is not None:
        s1 = processor(s1)
        s2 = processor(s2)

    if score_cutoff is None:
        score_cutoff = 0

    P_len = len(s1)
    T_len = len(s2)
    min_len = min(P_len, T_len)
    prefix = 0
    max_prefix = min(min_len, 4)

    for _ in range(max_prefix):
        if s1[prefix] != s2[prefix]:
            break
        prefix += 1

    jaro_score_cutoff = score_cutoff
    if (jaro_score_cutoff > 0.7):
        prefix_sim = prefix * prefix_weight

        if (prefix_sim >= 1.0):
            jaro_score_cutoff = 0.7
        else:
            jaro_score_cutoff = max(0.7, (prefix_sim - jaro_score_cutoff) / (prefix_sim - 1.0))

    Sim = jaro_similarity(s1, s2, score_cutoff=jaro_score_cutoff)
    if (Sim > 0.7):
        Sim += prefix * prefix_weight * (1.0 - Sim)

    return Sim if Sim >= score_cutoff else 0
```
pretty much look identical so am I missing something?

**Comment by maxbachmann** [comment]
> pretty much look identical so am I missing something?

No you are not missing anything :)
They are pretty much 1:1 copies of each other. I simply decided that it makes more sense to maintain all implementations in one place (inside the rapidfuzz/rapidfuzz-cpp repository). The C++ implementation is a bit different, since moving it into the same repository with the implementations of all other string metrics allowed me to reduce code duplication, but functionally they are identical.

**Comment by JoshuaBWT** [comment]
Thanks for the clarification, I will stick with rapidfuzz then

Once again, thanks for the amazing work 👍
